[project]
name = "west-ic-antenna"
version = "0.12.0"
description = "WEST ICRH Antenna Electrical Model"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipywidgets>=8.1.5",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "pytest>=8.3.3",
    "scikit-rf>=1.4.1",
]
