# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types:
      - created

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3

      - name: Set Up Python
        run: uv python install

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true

      - name: Build Package
        run: uv build

      - name: Publish to PyPi
        run: uv publish -v wheels/*
